//cart actions
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";

export const ADD_RESTAURANT = "ADD_RESTAURANT";
export const REMOVE_FROM_RESTAURANTS = "REMOVE_FROM_RESTAURANTS";
export const CLEAR_RESTAURANTS = "CLEAR_RESTAURANTS";

//wishlist actions
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const CLEAR_WISHLIST = "CLEAR_WISHLIST";

//log in/out actions
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";

//Restaurants list actions
export const FETCH_SUCCESS_RESTAURANTLIST = "FETCH_SUCCESS_RESTAURANTLIST";
export const FETCH_FAILURE_RESTAURANTLIST = "FETCH_FAILURE_RESTAURANTLIST";

//Orders
export const FETCH_SUCCESS_ORDERS = "FETCH_SUCCESS_ORDERS";
export const ADD_TO_ORDERS = "ADD_TO_ORDERS";
export const FETCH_FAILURE_ORDERS = "FETCH_FAILURE_ORDERS";
export const POST_SUCCESS_ORDERS = "POST_SUCCESS_ORDERS";
export const POST_FAIL_ORDERS = "POST_FAIL_ORDERS";



//saga actions
export const FETCH_SAGA_SUCCESS_RESTAURANTLIST = "FETCH_SAGA_SUCCESS_RESTAURANTLIST";
export const FETCH_SAGA_FAILURE_RESTAURANTLIST = " FETCH_SAGA_FAILURE_RESTAURANTLIST";
export const FETCH_SAGA_SUCCESS_ORDERS = "FETCH_SAGA_SUCCESS_ORDERS";
export const CANCEL_PREV_REQUESTS="CANCEL_PREV_REQUESTS"


//Loader
export const SET_LOADER="SET_LOADER";


